#:schema node_modules/wrangler/config-schema.json
name = "hotchair"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "hotchair-db"
database_id = "0619bef4-a009-443d-bc29-b533732427e5"
